DELIMITER $ 

CREATE OR REPLACE TRIGGER ITEM_MST_INSERT AFTER
    INSERT ON `ITEM_MST`
    FOR EACH ROW
BEGIN  
DECLARE I_WRSH_ID INT(11); 
DECLARE I_VRT_ID INT(11);

DECLARE WAREHOUSE_MST_CUR CURSOR FOR
     SELECT `WRHS_ID` FROM `WAREHOUSE_MST`;       

DECLARE VARIATION_MST_CUR CURSOR FOR
     SELECT `VRT_ID` FROM `VARIATION_MST`;       

OPEN WAREHOUSE_MST_CUR;  
    BEGIN  
    DECLARE WAREHOUSE_DONE INTEGER DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET WAREHOUSE_DONE = 1;
    WAREHOUSELOOP: LOOP
        FETCH WAREHOUSE_MST_CUR INTO I_WRSH_ID;
        IF WAREHOUSE_DONE = 1 THEN 
            LEAVE WAREHOUSELOOP;
        END IF;
    OPEN VARIATION_MST_CUR;   
    BEGIN 
    DECLARE VARIATION_DONE INTEGER DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VARIATION_DONE = 1; 
      VARIATIONLOOP: LOOP  
        FETCH VARIATION_MST_CUR INTO I_VRT_ID;  
        IF  VARIATION_DONE = 1 THEN 
           LEAVE VARIATIONLOOP;  
        END IF;  
            INSERT INTO `ITEM_STOCK_MST` (`ITEM_ID`,`VRT_ID`,`WRHS_ID`,`STOCK`,`ISM_CRTD_DATE`) VALUES (NEW.ITEM_ID,I_VRT_ID,I_WRSH_ID,0,SYSDATE());               
       END LOOP VARIATIONLOOP;   
       END; 
    CLOSE VARIATION_MST_CUR;     
    END LOOP WAREHOUSELOOP; 
    END ;  
CLOSE WAREHOUSE_MST_CUR; 
END $

DELIMITER ; 
 

