DELIMITER $ 

CREATE OR REPLACE TRIGGER VARIATION_MST_INSERT AFTER
    INSERT ON `VARIATION_MST`
    FOR EACH ROW
BEGIN  
DECLARE I_ITEM_ID INT(11);
DECLARE I_WRSH_ID INT(11); 

DECLARE ITEM_MST_CUR CURSOR FOR
     SELECT `ITEM_ID` FROM `ITEM_MST`;       

DECLARE WAREHOUSE_MST_CUR CURSOR FOR
     SELECT `WRHS_ID` FROM `WAREHOUSE_MST`;       


OPEN ITEM_MST_CUR;   
    BEGIN 
    DECLARE ITEM_DONE INTEGER DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET ITEM_DONE = 1; 
      ITEMLOOP: LOOP  
        FETCH ITEM_MST_CUR INTO I_ITEM_ID;  
        IF  ITEM_DONE = 1 THEN 
           LEAVE ITEMLOOP;  
        END IF;          
        OPEN WAREHOUSE_MST_CUR;  
            BEGIN  
            DECLARE WAREHOUSE_DONE INTEGER DEFAULT 0;
            DECLARE CONTINUE HANDLER FOR NOT FOUND SET WAREHOUSE_DONE = 1;
            WAREHOUSELOOP: LOOP
                FETCH WAREHOUSE_MST_CUR INTO I_WRSH_ID;
                IF WAREHOUSE_DONE = 1 THEN 
                    LEAVE WAREHOUSELOOP;
                END IF;
                INSERT INTO `ITEM_STOCK_MST` (`ITEM_ID`,`VRT_ID`,`WRHS_ID`,`STOCK`,`ISM_CRTD_DATE`) VALUES (I_ITEM_ID,NEW.VRT_ID,I_WRSH_ID,0,SYSDATE());
            END LOOP WAREHOUSELOOP; 
            END ;  
        CLOSE WAREHOUSE_MST_CUR;                    
       END LOOP ITEMLOOP;   
       END; 
    CLOSE ITEM_MST_CUR;     
END $

DELIMITER ; 
 

